shop/cart/urls.py
from django.conf.urls import include, url


urlpatterns = [
        url(r'^add/(?P<product_id>[0-9]+)/$', 'cart.views.add', name='add'),
        url(r'^remove/(?P<order_id>[0-9]+)/(?P<good_id>[0-9]+)/$', 'cart.views.remove', name='remove'),
        url(r'^edit/(?P<order_id>[0-9]+)/$', 'cart.views.edit', name='edit'),
        url(r'^status/(?P<order_id>[0-9]+)/(?P<status_id>[0-5]+)/$', 'cart.views.status', name='status'),
        url(r'^changeammount/(?P<order_id>[0-9]+)/(?P<good_id>[0-9]+)/$', 'cart.views.changeammount', name='changeammount'),
        url(r'^$', 'cart.views.index', name='index'),
        url(r'^history/$', 'cart.views.history', name='history'),
]

shop/products/urls.py
from django.conf.urls import include, url
from . import views



urlpatterns = [
        url(r'^$','products.views.mains'),
        url(r'^all/$', 'products.views.all', name='products'),
        url(r'^products/', include('products.urls', namespace="products")),
        url(r'^(?P<pk>[0-9]+)/$', 'products.views.showdetail', name='detail'),
        url(r'^(?P<product_id>[0-9]+)/vote/$', 'products.views.rating', name='vote'),
        url(r'^(?P<catslug>.+)/$', 'products.views.getLevItems', name='listcat'),
        url(r'^(?P<levslug>.+)/$', 'products.views.getItems', name='list'),
        url(r'^(?P<brand>.+)/$', 'products.views.getBrandItems'),
        url(r'^(?P<catslug>.+)/(?P<levslug>.+)/$', 'products.views.getItems'),
        url(r'^search/$', views.SearchView.as_view()),
       ]

shop/shop/urls.py
from orderslist import urls as orderslist_urls
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.conf.urls import include, url
from django.contrib import admin
from accounts import urls as accounts_urls
from products import urls as products_urls
from cookiecart import urls as cart_urls
from management import urls as management_urls
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$','products.views.index_view',name='home'),
    url(r'^accounts/', include(accounts_urls)),
    url(r'^products/', include(products_urls)),
    url(r'^management/', include(management_urls)),
    url(r'^cart/', include(cart_urls)),
]

if settings.DEBUG:

    if settings.MEDIA_ROOT:

        urlpatterns += static(settings.MEDIA_URL,

            document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

shop/products/models.py
# -*- coding: utf-8 -*-

#from djorm_pgfulltext.models import SearchManager
#from djorm_pgfulltext.fields import VectorField
from django.db import models
from sorl.thumbnail import ImageField
from django.contrib.sessions.models import Session
from django.utils import timezone

from accounts.models import AuthUser




# Create your models here.


class ProductCategory(models.Model):
    category_product_id = models.AutoField(primary_key=True)
    catslug = models.SlugField()
    category_product_name = models.CharField("Category_name", default=' none ', max_length=50)
    category_description = models.CharField("Category_description", default=' none ', max_length=200)

    class Meta:
        db_table = u'Categories'

    def __unicode__(self):
        return u" %s " % (self.category_product_name)


class ProductLevCategory(models.Model):
    levcategory_product_id = models.AutoField(primary_key=True)
    levcategory_product_name = models.CharField("SubCategory_name", default=' none ', max_length=50)
    levslug = models.SlugField()
    levcategory_description = models.CharField('SubCategory_desc', default=' none ', max_length=200)
    product_category = models.ForeignKey(ProductCategory)

    class Meta:
        db_table = u'LevCategories'

    def __unicode__(self):
        return u" %s " % (self.levcategory_product_name)

    @staticmethod
    def amount(self,products):
        amount=0
        for product in products:
            if product.product_levcategory == self:
                print amount
                amount=amount+1
        return amount


class ProductTags(models.Model):
    product_tags_id = models.AutoField(primary_key=True)
    product_tags_text = models.CharField("Tags_text", default=' ', max_length=50)

    class Meta:
        db_table = u'Tags'

    def __unicode__(self):
        return u" %s " % (self.product_tags_text)


class ProductRating(models.Model):
    product_rating_id = models.AutoField(primary_key=True)
    product_rating = models.FloatField("Rating of products", default='0')

    class Meta:
        db_table = u'Rating'

    def __unicode__(self):
        return u" %s " % (self.product_rating)


class ProducerProduct(models.Model):
    producer_product_id = models.AutoField(primary_key=True)
    producer_product_name = models.CharField("Producer_name", default='Purina', max_length=50)

    class Meta:
        db_table = u'Producers'

    def __unicode__(self):
        return u" %s " % (self.producer_product_name)


class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(null=True, blank=True)
    adddescription = models.TextField(null=True, blank=True)
    price = models.DecimalField(decimal_places=2, max_digits=100, default=29.99)
    sale_price = models.DecimalField(decimal_places=2, max_digits=100,default=0)

    slug = models.SlugField()
    timestamp = models.DateTimeField(auto_now_add=True, auto_now=False)
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)
    active = models.BooleanField(default=True)
    product_producer = models.ForeignKey(ProducerProduct)
    product_levcategory = models.ForeignKey(ProductLevCategory)
    product_tags = models.ForeignKey(ProductTags)
    product_rating = models.DecimalField(decimal_places=2, max_digits=3,default=0)
    product_vote = models.DecimalField(decimal_places=0,max_digits=3, default=0)
    urllink = models.URLField(blank=True)
    product_image= ImageField(upload_to='products/static/im/')

    created_at = models.DateTimeField("When_created", auto_now_add=True, auto_now=False)
    updated_at = models.DateTimeField("When _updated", auto_now_add=False, auto_now=True)


    def __unicode__(self):
        return self.title

    class Meta:
        ordering = ['-created_at']
        unique_together = ('title', 'slug')

    def get_price(self):
        return self.price






class Review(models.Model):
    user = models.OneToOneField(AuthUser, null=True)
    session = models.OneToOneField(Session, null=True)

    def __unicode__(self):
        if self.user:
            return u'{} review'.format(self.user)
        elif self.session:
            return u'{} review'.format(self.session.pk)
        else:
            return None


class ProductComments(models.Model):
    review = models.ForeignKey(Review)
    product_comments_id = models.AutoField(primary_key=True, unique=True)
    product_comments_text = models.TextField("Product_comments_text")  # possible widget if any
    auth_username = models.ForeignKey(AuthUser)
    idprod = models.ForeignKey(Product)  #link to existing id in Product

    class Meta:
        db_table = u'Comments'

    def __unicode__(self):
        return "%s %s " % (self.pk, self.product_comments_text)


    def __str__(self):
        return "%s %s " % (self.pk, self.product_comments_text)

shop/templates/base_detail_old.html
{% load staticfiles %}

{% load thumbnail %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block head_title %}Магазин{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
      <style>
    {% block styles %}
    {% endblock %}
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  {% block navbar %}
      {% include "navbar.html" %}
  {% endblock %}
{% block content %}


<div class="row">
<div class="col-md-3">

<ul>

 {% for productcategory in categorys %}

<ul class="nav nav-stacked">
                <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#userMenu{{ productcategory.category_product_id }}">{{  productcategory.category_product_name  }}
                    <i class="glyphicon glyphicon-chevron-down"></i></a>
                    <ul class="nav nav-stacked collapse in" id="userMenu{{ productcategory.category_product_id }}">


                   {% for levproductcategory in subcategorys %}


                       {% if  levproductcategory.product_category == productcategory %}


                        <li class="active">  <a href="{% url 'list' levproductcategory.levslug %} ">  <i class="glyphicon glyphicon-triangle-right"></i>
                            {{  levproductcategory.levcategory_product_name }}  <span class="badge"> {{ levproductcategory.product_set.count}} </span>  </a></li>


                    {% endif %}

                    {% endfor %}


            </ul>
                </li>
  {% endfor %}

</ul>

</ul>

</div>  <!-- col-md-3-->

<div class="col-md-9">


    <div class="well">

  <ul class="breadcrum">
    <li class="active"> Категория:  {{ catname }}  <span class="divider">/</span>  </a>  <a href=" {% url 'list' mlevslug %} " > Раздел: {{ sublev }} </a>  </li>
  </ul>
    </div>  <!--   well   -->


   <div class="col-md-5">

                        <center>
                 {% thumbnail product.product_image "275x275" crop="center" as im %}
                   <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                 {% endthumbnail %}

    </div>

<div class="col-md-6">

 <div style ='color:#ffbb68; ' >
<h3>  {{ product.title }}  {{ product.price }} </h3>
<ul>
</ul>

<ul>
</ul>

</div>
<p>
</p>

<p>
</p>

<ul>
</ul>


 <form action="/cart/add/{{product.id }}/ " method="post">
{% csrf_token %}
<h5>
<input type="submit" value="Добавить в корзину" /> </h5>

</form>

</div>

<h5>  Производитель :  {{ product.product_producer   }}   </h5>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<p>
<h5> Общая оценка:   {{ product.product_rating   }}    Количество голосов: {{ product.product_vote  }}  </h5>
    </p>

{% if showres == 1 %}

<form action="{% url 'products:vote' product.id %}" method="post">
{% csrf_token %}

  <ul class="horList side">
          Оценка :

          <label>
              <input type="radio" name="ans_num" value="1.0" id="RadioGroup1_1" onclick="submit(product.product_rating);">
              1</label>

          <label>
              <input type="radio" name="ans_num" value="2.0" id="RadioGroup1_2" onclick="submit(product.product_rating);">
              2</label>

           <label>
              <input type="radio" name="ans_num" value="3.0" id="RadioGroup1_3" onclick="submit(product.product_rating);">
              3</label>

            <label>
              <input type="radio" name="ans_num" value="4.0" id="RadioGroup1_4" onclick="submit(product.product_rating);">
              4</label>

             <label>
              <input type="radio" name="ans_num" value="5.0" id="RadioGroup1_5" onclick="submit(product.product_rating);">
              5</label>

        </ul>

    <p><b>Добавьте ваш отзыв:</b></p>
    <p> <textarea rows="1" cols="55" name="comment_text"></textarea></p>

<h5>
<input type="submit" value="Ваша оценка" /> </h5>

</form>

{% endif %}


<div class="row">


   <div class="col-md-12">


  <div class="well">  </div>

   <div class="col-md-9">

                <ul class="nav nav-tabs">

                        <li><a href="#description" data-toggle="tab">Описание</a></li>

                        <li><a href="#char" data-toggle="tab">Характеристики</a></li>

                        <li><a href="#com" data-toggle="tab">Отзывы</a></li>

                </ul>



                <div class="tab-content">

                        <div class="tab-pane" id="description"> <p> {{product.description }} </p> </div>

                        <div class="tab-pane" id="char"><p> {{ product.adddescription }}  </p></div>

                        <div class="tab-pane" id="com"><p> {{ comments|linebreaks  }}  </p> </div>

                </div>

            </div>
        </div>
</div>
</div>

{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js"%}"></script>
  </body>
</html>

shop/templates/base_test.html
{% load staticfiles %}

{%  load amount %}

{% load thumbnail %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block head_title %}Магазин{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
      <style>
    {% block styles %}
    {% endblock %}
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  {% block navbar %}
      {% include "navbar.html" %}
  {% endblock %}

  {% block content %}

   <nav class="navbar navbar-inverse" role="navigation" id="categories-navbar">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#categories-navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        </button>
                    </div>


 <div class="collapse navbar-collapse" id="categories-navbar-collapse">
                        <ul class="nav navbar-nav">


             {% for productcategory in categorys %}
             <li>
              <a href="#"><span class="glyphicon glyphicon-chevron-right"></span> {{  productcategory.category_product_name  }}

                  {% if sublev != 'No results' and sublev != 'Catalog' and productcategory == mainlev %}

                  <ul class="nav collapse in" id="userMenu{{ productcategory.category_product_id }}">

                 {%  endif %}

                 {% if sublev != 'No results' and sublev != 'Catalog' and productcategory != mainlev %}

                    <ul class="nav collapse" id="userMenu{{ productcategory.category_product_id }}">

                 {%  endif %}

                 </a></li>

                {% endfor %}
              </ul>
           </div>
 </nav>


  <div class="row">
   <div class="col-sm-3">

    <ul>

      {% for productcategory in categorys %}

        <ul class="nav nav-stacked">
                <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#userMenu{{ productcategory.category_product_id }}">{{  productcategory.category_product_name  }}
                    <i class="glyphicon glyphicon-chevron-down"></i></a>

                 {% if sublev != 'No results' and sublev != 'Catalog' and productcategory == mainlev %}

                    <ul class="nav nav-stacked collapse in" id="userMenu{{ productcategory.category_product_id }}">

                 {%  endif %}

                 {% if sublev != 'No results' and sublev != 'Catalog' and productcategory != mainlev %}

                    <ul class="nav nav-stacked collapse" id="userMenu{{ productcategory.category_product_id }}">

                 {%  endif %}

                  {% for levproductcategory in subcategorys %}


                       {% if  levproductcategory.product_category == productcategory %}


                       {% if  sublev != 'No results'  %}
                        <li class="active"> <a href="{% url 'list' levproductcategory.levslug %} ">  <i class="glyphicon glyphicon-triangle-right"></i>

                            {{ levproductcategory.levcategory_product_name }}  <span class="badge"> {{ levproductcategory.product_set.count}} </span>   </a></li>

                       {% endif %}

                       {% if sublev == 'No results'  %}
                        <li class="active"> <a href="{% url 'list' levproductcategory.levslug %} ">  <i class="glyphicon glyphicon-triangle-right"></i>

                            {{ levproductcategory.levcategory_product_name }}  <span class="badge"> {%  get_amount levproductcategory products  %} </span> </a></li>

                       {% endif %}

                        {% endif %}

                   {% endfor %}


                    </ul>
                </li>
      {% endfor %}

</ul>
    <ul>


</div>


     <div class="col-sm-9">


    {% if items|length > 0  %}

        {% if sublev == 'No results' and sublev != 'Catalog'  %}

             <div class="well well-sm"> Результаты поиска: на запрос: {{ querysea }} </div>

        {% endif %}

         {% if sublev != 'No results' and sublev != 'Catalog'  %}

         <div class="well well-sm"> Раздел товара:  {{ sublev }}  </div>

          {% endif %}

         {% if sublev == 'Catalog' %}

         <div class="well well-sm"> Общий каталог товаров интернет-магазина: Все товары по категориям  </div>

          {% endif %}


    {% endif %}
    <div id="product">
               {% for product in page_obj  %}

                  {% if product.product_levcategory.product_category.category_product_name == namecat  %}

                       {{  product.product_levcategory.product_category.category_product_name }}
                   {% endif%}


                    <div class="col-sm-9 col-md-4">
                        <div class="thumbnail">

                             {% thumbnail product.product_image "220x180" crop="center" as im %}
                                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{  product.title}}" >
                             {% endthumbnail %}
                                <div class="caption">
                                <h5>  {{ product.title   }}   </h5>

                              <form action="/cart/add/{{product.id }}/ " method="post">
                             {% csrf_token %}
                                  <center>

                                 <a href="{% url 'products:detail' product.id %} " class=" btn btn-default " aria-label="Center Align" >О товаре <span class="glyphicon glyphicon-check" > </span> </a>

                            <input type="submit" value="В корзину {{ product.price }}"class=" btn-sm btn-primary "   >
                              </center>

                              </form>

                                  <p> </p>
                                  <p> Производитель :  {{ product.product_producer }}  </p>


                                 </div>
                         </div>

                     </div>

               {% endfor %}



     <div class="row">

     <div class="col-md-12 text-center">

  {% if page_obj|length != 0  and page_obj|length > 8 %}
  <ul class="pagination pagination ">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><a href="#">&laquo;</a></li>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% ifequal num page_obj.number %}
        <li class="active"><a href="#">{{ num }}<span class="sr-only">(current)</span></a></li>
      {% else %}
        <li><a href="?page={{ num }}">{{ num}}</a></li>
      {% endifequal %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><a href="#">&raquo;</a></li>
    {% endif %}
  </ul>
{% endif %}
  </div>

    </div>

     </div>

    </div>

 {% block sidebar %}


  {% endblock %}


{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js"%}"></script>
  </body>
</html>

shop/templates/base_withoutp.html
{% load staticfiles %}

{% load thumbnail %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block head_title %}Магазин{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
    <link href="{% static "css/custom.css" %}" rel="stylesheet">
      <style>
    {% block styles %}
    {% endblock %}
    </style>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
  {% block navbar %}
      {% include "navbar.html" %}
  {% endblock %}
{% block content %}


<div class="row">
<div class="col-sm-3">

<ul>

 {% for productcategory in categorys %}

<ul class="nav nav-stacked">
                <li class="nav-header"> <a href="#" data-toggle="collapse" data-target="#userMenu{{ productcategory.category_product_id }}">{{  productcategory.category_product_name  }}
                    <i class="glyphicon glyphicon-chevron-down"></i></a>
                    <ul class="nav nav-stacked collapse in" id="userMenu{{ productcategory.category_product_id }}">


                   {% for levproductcategory in subcategorys %}


                       {% if  levproductcategory.product_category == productcategory %}


                        <li class="active"> <a href="{% url 'list' levproductcategory.levslug %} ">  <i class="glyphicon glyphicon-triangle-right"></i>
                            {{  levproductcategory.levcategory_product_name }}  <span class="badge"> {{ levproductcategory.product_set.count}} </span>  </a></li>


                    {% endif %}

                    {% endfor %}


            </ul>
                </li>
  {% endfor %}

</ul>
    <ul>


</div>


     <div class="col-sm-9"   </div>


    {% if items|length > 0  %}

        {% if sublev == 'No results' %}

             <div class="well"> Результаты поиска: на запрос: {{ querysea }} </div>

        {% endif %}

         {% if sublev != 'No results' %}

         <div class="well"> Раздел товара:  {{ sublev }} </div>

          {% endif %}

    {% endif %}
               {% for product in items  %}

                    <div class="col-sm-3">

                        <center>
                       {% thumbnail product.product_image "225x225" crop="center" as im %}
                           <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                      {% endthumbnail %}

                        <a href="{% url 'products:detail' product.id %}">  {{ product.title }} {{ product.price }}     </a>

                        <p> Производитель :  {{ product.product_producer }}  </p>

                     </form>

                   <form action="/cart/add/{{product.id }}/ " method="post">
                   {% csrf_token %}

                   <input type="submit" value="Добавить в корзину" />

                   </form>

                        </center>

                  </div>

               {% endfor %}


</div>

 {% block sidebar %}


  {% endblock %}


{% endblock %}

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js"%}"></script>
  </body>
</html>

shop/templates/catalog.html
{% extends 'base.html' %}
{% load staticfiles %}

    {% block category-tree %}

    {% endblock %}
